Homework 1 - Eclectic Eagle Scouts
========================================================
```{r}
##test data##
graph1 = list(A = list(edges   = c(2L),
                       weights = c(1 )),
              B = list(edges   = c(3L),
                       weights = c(1 )),
              C = list(edges   = c(5L),
                       weights = c(1 )),
              D = list(edges   = c(2L),
                       weights = c(1 )),
              E = list(edges   = c(4L,6L),
                       weights = c(1,1  )),
              F = list(edges   = c(),
                       weights = c())
             )
graph2 = list(A = list(edges   = c(2L),
                       weights = c(14)),
              B = list(edges   = c(3L,4L),
                       weights = c(23,13)),
              D = list(edges   = c(1L),
                       weights = c(5) ),
              F = list(edges   = c(1L,5L),
                       weights = c(43,33)),
              N = list(edges   = c(1L,2L,4L),
                       weights = c(33,22,11))
             )
```

```{r}
##1. Function - is_valid
is_valid <- function(g){
  count <- 0
##Check if there are names for the primary list that they are all unique
primary <- names(g)
if (sum(duplicated(primary)) != 0){count=count+1}
for (i in 1 : length(g)){
##Check that object is a list of lists
  if (typeof(g[[i]])!="list") {count=count+1}
##Check that each secondary list contains only edges and weights vectors 
  if (length(g[[i]])!=2) {count=count+1}
  if (names(g[[i]])[1]!="edges") {count=count+1}
  if (names(g[[i]])[2]!="weights") {count=count+1}
##Check that edges and weights vectors that are of the appropriate type
  if (!is.null(g[[i]][[1]])){
     if (!is.vector(g[[i]][[1]])) {count=count+1}
    if (!is.integer(g[[i]][[1]])) {count=count+1}
    if (min(g[[i]][[1]]) <= 0) {count=count+1}
    if (!is.numeric(g[[i]][[2]])) {count=count+1}
##Check that there are not any edges to non-existent vertices
  if (max(g[[i]][[1]])>length(g))  {count=count+1}
##Check that all weights are not less than or equal to 0
  if (min(g[[i]][[2]])<=0) {count=count+1}
##Check that every edge has a weight
  if (length(g[[i]][[1]]) != length(g[[i]][[2]])){count=count+1}
}
}
##As long as "count" is not equal to zero, there must be a mistake somewhere
if (count == 0) {print ("TRUE")}
  else {print("FALSE")}
}
is_valid(graph1)
is_valid(graph2)
```
